app:
 image: jaequery/honeybadger
 links:
 - db:honeybadger-postgres
 command: /app/bin/docker/init.sh
 environment:
 - VIRTUAL_HOST=markett.io,markett.app
# restart: always
 volumes:
 - .:/app
 #- ./gems:/usr/local/bundle/gems
db:
 image: postgres
 environment:
 - POSTGRES_PASSWORD=j
# restart: always
