app:
 image: jaequery/honeybadger
 links:
 - db:honeybadger-postgres
 command: /app/bin/docker/init.sh
 environment:
 - VIRTUAL_HOST=markett.app
 - RACK_ENV=development
 - BUNDLE_PATH=/app/volumes/bundler
 volumes:
 - .:/app
 tty: true
 #restart: always 

db:
 image: postgres
 environment:
 - POSTGRES_PASSWORD=j
 volumes:
 - pgdata:/var/lib/postgresql/data 
 ports:
 - "5432:5432"
 #restart: always
