app:
 image: jaequery/honeybadger
 links:
 - db:honeybadger-postgres
 - memcache:memcache
 command: /app/bin/docker/init.sh
 environment:
 - VIRTUAL_HOST=markett.docker,markett.io,www.markett.io,markett.com,www.markett.com
 - RACK_ENV=development
 - BUNDLE_PATH=/app/volumes/bundler
 volumes:
 - .:/app
 #tty: true
 #restart: always 

db:
 image: postgres
 environment:
 - POSTGRES_PASSWORD=j
 volumes:
 - pgdata:/var/lib/postgresql/data 
 - ./sql:/sql
 ports:
 - "5432:5432"
 #restart: always

memcache:
 image: memcached
 ports:
 - "11211:11211"

# mongo:
#  image: mongo
#  ports:
#  - "27017:27017"